OmniError, getting users/roles by id/handle
debatecore/tau pull request #41
Opened 2024-12-23 00:15 UTC by jakubmanczak

Closes #20

2024-12-29 13:06 UTC, Mateusz-Dobrzynski requested changes
Why is the `.sqlx` directory in the PR?

2024-12-29 13:06 UTC, Mateusz-Dobrzynski commented on src/users/auth/mod.rs
> +pub const AUTH_SESSION_COOKIE_NAME: &str = "tausession";
```suggestion
pub const AUTH_SESSION_COOKIE_NAME: &str = "tau_session";
```

2024-12-29 13:31 UTC, jakubmanczak commented on src/users/auth/mod.rs
> +pub const AUTH_SESSION_COOKIE_NAME: &str = "tausession";
Pointless! Pointless! Pointless! Pointless! Pointless! Pointless! 
![12bd37435510559b03afad1929277d2bf62e809c_hq-3957523440](https://github.com/user-attachments/assets/53eab1dd-26b9-4646-919a-ec29a70ece10)

2024-12-29 13:33 UTC, jakubmanczak commented on src/omni_error.rs
> +    fn clerr(&self) -> String {
https://github.com/user-attachments/assets/4488326f-60a1-4a57-a422-7cce9258346f

2024-12-29 13:35 UTC, jakubmanczak commented
> Why is the `.sqlx` directory in the PR?

Because tests will fail if it isn't. We're using compiletime checked queries, and the github test runner has no context to check them against. If we don't provide it with info on what the queries look like, it will fail like it already did at least once on this branch when i forgot to include them.

There's other solutions, this is the easiest one for now.

2024-12-29 13:40 UTC, jakubmanczak commented on src/omni_error.rs
> +    fn clerr(&self) -> String {
(I am welcome to suggestions that preserve compactness while increasing readability)

2025-01-02 09:26 UTC, jakubmanczak commented
Current status: I forgot about the README and hashing the tokens in the database. Whoops!

2025-01-11 18:07 UTC, Mateusz-Dobrzynski approved these changes

2025-01-12 12:11 UTC, merged